id: A85DA8B0A
title: Aspiration to Follow the Gurus of the Ngor Tradition
type: translation
pechas:
- I099166A9
- I4437DD67
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:53.986336
  last_modified_at: 2023-01-04 12:06:53.986351
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I099166A9/E9AE: 1E2B
  I4437DD67/5862: 1E2B
